### ISSUE TITLE
Costumize Back Half

### ISSUE THREAD

**Issue by wulandrima1** [phplicengine/bitly#12]
how to costumize back half

Ex :
Url : https://www.google.com/
Show : bit.ly/G1gh7

How to costumize **bit.ly/G1gh7-Google-com**

**Comment by phplicengine** [comment]
You have to use `addCustomBitlink()` in Custom service: https://github.com/phplicengine/bitly/blob/4a6089357725fd2d7b3e3e296deb258319396105/lib/PHPLicengine/Service/Custom.php#L58-L65
However there is one important limit on this endpoint which requires the original link to be under a custom domain. Bitly does not allow users to add custom back halves to "bit.ly" links through the API to prevent any automated abuse on that domian.
However, if you have a custom domain attached to your account you could add a custom back half to something like example.ws/G1gh7 ->example.ws/G1gh7-Google-Com.
